languageCode = "en"
languageName = "English"
weight = 1
title = "PolanaTech"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = ""

[params.author]
  name = "Roberto Polana"
  email = "robertopolana@gmail.com"
  image = "img/blowfish_logo.png"
  headline = ""
  bio = ""
  links = [
    { github = "https://github.com/robertopolana" },
  ]