languageCode = "it"
languageName = "Italiano"
weight = 4
title = "PolanaTech"

[params]
  displayName = "Italiano"
  isoCode = "it"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.png"
  description = ""

[params.author]
  name = "Roberto Polana"
  email = "robertopolana@gmail.com"
  image = "img/profilefoto.png"
  headline = ""
  bio = ""
  links = [
    { github = "https://github.com/robertopolana" },
    { linkedin = "https://www.linkedin.com/in/roberto-polana-65b431135/" },
  ]