languageCode = "it"
languageName = "Italiano"
weight = 4
title = "PolanaTech"

[params]
  displayName = "Italiano"
  isoCode = "it"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = ""

[params.author]
  name = "Roberto Polana"
  email = "robertopolana@gmail.com"
  image = "img/blowfish_logo.png"
  headline = ""
  bio = ""
  links = [
    { github = "https://github.com/robertopolana" },
  ]