languageCode = "it"
languageName = "Italiano"
weight = 4
title = "PolanaTech"

[params]
  displayName = "Italiano"
  isoCode = "it"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "Un potente, leggero tema per Hugo."

[params.author]
  name = "PolanaTech"
  image = "img/blowfish_logo.png"
  headline = ""
  bio = ""
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]