languageCode = "en"
languageName = "English"
weight = 1
title = "PolanaTech"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = ""

[params.author]
  name = "PolanaTech"
  email = "robertopolana@gmail.com"
  image = "img/blowfish_logo.png"
  headline = ""
  bio = ""
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]